/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ModelsRouteRouteImport } from './routes/models/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as ModelsLocalRouteImport } from './routes/models/local'

const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRouteRoute = ModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRouteRoute,
} as any)
const ModelsLocalRoute = ModelsLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => ModelsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models': typeof ModelsRouteRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/models/local': typeof ModelsLocalRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/models/local': typeof ModelsLocalRoute
  '/models': typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models': typeof ModelsRouteRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/transcripts': typeof TranscriptsRoute
  '/models/local': typeof ModelsLocalRoute
  '/models/': typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models'
    | '/meetings'
    | '/settings'
    | '/transcripts'
    | '/models/local'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/meetings'
    | '/settings'
    | '/transcripts'
    | '/models/local'
    | '/models'
  id:
    | '__root__'
    | '/'
    | '/models'
    | '/meetings'
    | '/settings'
    | '/transcripts'
    | '/models/local'
    | '/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsRouteRoute: typeof ModelsRouteRouteWithChildren
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptsRoute: typeof TranscriptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRouteRoute
    }
    '/models/local': {
      id: '/models/local'
      path: '/local'
      fullPath: '/models/local'
      preLoaderRoute: typeof ModelsLocalRouteImport
      parentRoute: typeof ModelsRouteRoute
    }
  }
}

interface ModelsRouteRouteChildren {
  ModelsLocalRoute: typeof ModelsLocalRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteRouteChildren: ModelsRouteRouteChildren = {
  ModelsLocalRoute: ModelsLocalRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteRouteWithChildren = ModelsRouteRoute._addFileChildren(
  ModelsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsRouteRoute: ModelsRouteRouteWithChildren,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  TranscriptsRoute: TranscriptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
