export const MANUAL_FALLBACK_TIMEOUT_MS = 10_000
export const AUTO_PASTE_MAX_ATTEMPTS = 2
export const AUTO_PASTE_RETRY_DELAY_MS = 200
export const CLIPBOARD_RESTORE_DELAY_AFTER_PASTE_MS = 420
export const CLIPBOARD_RESTORE_DELAY_AFTER_PASTE_LAST_MS = 700
export const CLIPBOARD_RESTORE_DELAY_AFTER_MANUAL_PASTE_MS = 900
export const MANUAL_SHORTCUT_REPLAY_DELAY_MS = 45
export const POST_PASTE_TARGET_PROBE_TIMEOUT_MS = 120
