export const MANUAL_FALLBACK_TIMEOUT_MS = 10_000
export const CLIPBOARD_RESTORE_DELAY_AFTER_PASTE_MS = 420
export const CLIPBOARD_RESTORE_DELAY_AFTER_MANUAL_PASTE_MS = 900
export const MANUAL_SHORTCUT_REPLAY_DELAY_MS = 45
